#!/bin/sh
NEO_GIT_GRAPH_ASKPASS_PIPE=`mktemp`
NEO_GIT_GRAPH_ASKPASS_PIPE="$NEO_GIT_GRAPH_ASKPASS_PIPE" "$NEO_GIT_GRAPH_ASKPASS_NODE" "$NEO_GIT_GRAPH_ASKPASS_MAIN" $*
cat $NEO_GIT_GRAPH_ASKPASS_PIPE
rm $NEO_GIT_GRAPH_ASKPASS_PIPE
