/**
 * Emoji shortcode replacement for commit messages, e.g. `:tada:` -> 🎉.
 *
 * This bundles the most common GitHub / gitmoji shortcodes. Users can add or
 * override any mapping through the `git-graph-alter.customEmojiShortcodeMappings`
 * setting.
 */
const EMOJI_SHORTCODES: { [code: string]: string } = {
  // gitmoji (https://gitmoji.dev) — frequently used in commit subjects
  art: "🎨",
  zap: "⚡",
  fire: "🔥",
  bug: "🐛",
  ambulance: "🚑",
  sparkles: "✨",
  memo: "📝",
  rocket: "🚀",
  lipstick: "💄",
  tada: "🎉",
  white_check_mark: "✅",
  lock: "🔒",
  closed_lock_with_key: "🔐",
  bookmark: "🔖",
  rotating_light: "🚨",
  construction: "🚧",
  green_heart: "💚",
  arrow_down: "⬇️",
  arrow_up: "⬆️",
  pushpin: "📌",
  construction_worker: "👷",
  chart_with_upwards_trend: "📈",
  recycle: "♻️",
  heavy_plus_sign: "➕",
  heavy_minus_sign: "➖",
  wrench: "🔧",
  hammer: "🔨",
  globe_with_meridians: "🌐",
  pencil2: "✏️",
  poop: "💩",
  rewind: "⏪",
  twisted_rightwards_arrows: "🔀",
  package: "📦",
  alien: "👽",
  truck: "🚚",
  page_facing_up: "📄",
  boom: "💥",
  bento: "🍱",
  wheelchair: "♿",
  bulb: "💡",
  beers: "🍻",
  speech_balloon: "💬",
  card_file_box: "🗃️",
  loud_sound: "🔊",
  mute: "🔇",
  busts_in_silhouette: "👥",
  children_crossing: "🚸",
  building_construction: "🏗️",
  iphone: "📱",
  clown_face: "🤡",
  egg: "🥚",
  see_no_evil: "🙈",
  camera_flash: "📸",
  alembic: "⚗️",
  mag: "🔍",
  label: "🏷️",
  seedling: "🌱",
  triangular_flag_on_post: "🚩",
  goal_net: "🥅",
  dizzy: "💫",
  wastebasket: "🗑️",
  passport_control: "🛂",
  adhesive_bandage: "🩹",
  monocle_face: "🧐",
  coffin: "⚰️",
  test_tube: "🧪",
  necktie: "👔",
  stethoscope: "🩺",
  bricks: "🧱",
  technologist: "🧑‍💻",
  money_with_wings: "💸",
  thread: "🧵",
  safety_vest: "🦺",
  // common GitHub shortcodes
  "+1": "👍",
  "-1": "👎",
  smile: "😄",
  smiley: "😃",
  grin: "😁",
  laughing: "😆",
  joy: "😂",
  rofl: "🤣",
  wink: "😉",
  blush: "😊",
  heart_eyes: "😍",
  thinking: "🤔",
  thumbsup: "👍",
  thumbsdown: "👎",
  ok_hand: "👌",
  clap: "👏",
  raised_hands: "🙌",
  pray: "🙏",
  muscle: "💪",
  wave: "👋",
  eyes: "👀",
  heart: "❤️",
  broken_heart: "💔",
  star: "⭐",
  star2: "🌟",
  warning: "⚠️",
  x: "❌",
  heavy_check_mark: "✔️",
  question: "❓",
  exclamation: "❗",
  100: "💯",
  tada2: "🎊",
  gift: "🎁",
  hourglass: "⌛",
  watch: "⌚",
  calendar: "📅",
  clipboard: "📋",
  books: "📚",
  book: "📖",
  computer: "💻",
  keyboard: "⌨️",
  printer: "🖨️",
  email: "📧",
  inbox_tray: "📥",
  outbox_tray: "📤",
  link: "🔗",
  key: "🔑",
  gear: "⚙️",
  nut_and_bolt: "🔩",
  battery: "🔋",
  electric_plug: "🔌",
  magnet: "🧲",
  shield: "🛡️",
  crystal_ball: "🔮",
  dart: "🎯",
  game_die: "🎲",
  snowflake: "❄️",
  sunny: "☀️",
  cloud: "☁️",
  zzz: "💤",
  checkered_flag: "🏁",
  trophy: "🏆",
  medal: "🏅",
  fire_engine: "🚒",
  ship: "🚢",
  airplane: "✈️",
  car: "🚗",
  bike: "🚲",
  turtle: "🐢",
  snail: "🐌",
  whale: "🐳",
  octocat: "🐙",
  cat: "🐱",
  dog: "🐶",
  penguin: "🐧",
  bird: "🐦",
  ant: "🐜",
  honeybee: "🐝",
  ladybug: "🐞",
  hatching_chick: "🐣",
  apple: "🍎",
  lemon: "🍋",
  cherries: "🍒",
  pizza: "🍕",
  hamburger: "🍔",
  cake: "🍰",
  birthday: "🎂",
  cookie: "🍪",
  coffee: "☕",
  tea: "🍵",
  beer: "🍺",
  wine_glass: "🍷",
  champagne: "🍾"
};

/**
 * Replace `:shortcode:` tokens in `text` with their emoji. `custom` entries
 * (keyed by shortcode without surrounding colons) take precedence over the
 * built-in map. Unknown shortcodes are left untouched.
 */
export function replaceEmojiShortcodes(
  text: string,
  custom: { [code: string]: string } = {}
): string {
  return text.replace(/:([\w+-]+):/g, (match, code: string) => {
    const emoji = code in custom ? custom[code] : EMOJI_SHORTCODES[code];
    return emoji !== undefined ? emoji : match;
  });
}
